"use client"

import type { Metadata } from "next";
import { useEffect, useState } from "react";
import SplashScreen from "./Organisms/SplashScreen";
import Footer from "./Organisms/Footer";
import Navbar from "./Organisms/Navbar";

export const metadata: Metadata = {
  title: "Green Hills Academy",
  description: "Generated by Green Hills Academy",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false);
    }, 1000);
    return () => clearTimeout(timer);
  }, []);

  return (
    <div>
      {loading ? (
        <SplashScreen />
      ) : (
        <div>
          <Navbar />
          {children}
          <Footer />
        </div>
      )}
    </div>
  );
}
