export const universities = [
    "Harvard University",
    "Yale University",
    "Berkeley University",
    "Stanford University",
    "Purdue University",
    "Rice University",
    "Cornell University",
    "Kent State University",
    "Umass Boston",
    "Reed College",
    "Sunny Plattsburgh University",
    "Hope College",
    "Pomona College",
    "Drexel University",
    "Drake University",
    "University of Buffalo",
    "North Carolina State University",
    "Michigan State University",
    "University of Kentucky",
    "Arkansas University",
    "Massachusetts Institute of Technology",
    "University of Oklahoma",
    "University of Houston",
    "Rollins University",
    "Lynn University",
    "Stony Brook University",
    "Arizona State University",
    "Texas A&M",
    "Oklahoma Christian University",
    "University of Miami",
    "Grand Canyon College",
    "Penn State University",
    "University of Cincinnati",
    "Rice University",
    "Northeastern University",
    "Pratt Institute",
    "University of Washington",
    "Boston University",
    "Marist College",
    "Brock University",
    "University of New Haven",
    "Temple University",
    "Sacred Heart University",
    "Johns Hopkins University",
    "Columbia College",
    "Auburn University",
    "Kansas State University",
    "Amherst College",
    "Princeton University",
    "University of Wisconsin",
    "Dartmouth College",
    "Lafayette University",
    "Williams College",
    "Connecticut College",
    "University of Richmond",
    "Swarthmore College",
    "Tufts College",
    "Colby College",
    "Union College",
    "Depauw University",
    "Western Michigan University",
    "Bucknell University",
    "Haverford College",
    "Rochester Institute of Technology",
    "Fordham University",
    "Nova Southeastern University",
    "Babson College",
    "New York University",
    "Syracuse University",
    "Baylor University",
    "Gustavus College",
    "Lehigh University",
    "Duquesne University",
    "University of Houston College",
    "University of Tampa",
    "Rider University",
    "Phoenix University",
    "Savannah School of Arts & Design",
    "College of Holy Cross",
    "Columbia University",
    "NYU Abu Dhabi",
    "Carnegie Mellon University",
    "Iowa State University",
    "Brown University",
    "Sunny Stony Brook University",
    "University of Hult",
    "College of Wooster",
    "Loyola University",
    "University of Connecticut",
    "University of Pittsburgh",
    "University of North Texas",
    "University of Houston",
    "Sunny Buffalo University",
    "Skidmore College",
    "University of Washington",
    "University of Southern Mississippi",
    "Birmingham Southern College",
    "Xavier University",
    "University of Massachusetts",
    "Florida Institute of Technology",
    "Florida Atlantic University",
    "Michigan Technological University",
    "University of Miami",
    "Rhode Island College",
    "Tulane University",
  
    "Carleton University",
    "University of British Columbia",
    "McGill University",
    "University of Toronto",
    "Prince Edward University",
    "Concordia University",
    "University of Windsor",
    "Manitoba University",
    "McMaster University",
    "McEwan University",
    "York University",
    "Lakehead University",
    "University of Calgary",
    "University of Ottawa",
    "Trent University",
    "Queens University",
    "University of Alberta",
    "Wilfred Laurier University",
    "University of Saskatchewan",
    "Simon Fraser University",
    "Toronto Metropolitan University",
    "Dalhousie University",
    "Western University",
    "Waterloo University",
    "Seneca College",
    "Ontario Tech University",
    "University of Guelph-Humber",
    "Algoma University",
    "Thompson Rivers University",
    "St. Mary's University",
    "Windsor University",
    "Mount Allison University",
    "University of Regina",
    "St. Mary's University",
    "Brock University",
    "University of Victoria",
    "University of Winnipeg",
    "Niagara College",
    "Fanshawe College",
    "Centennial College",
    "Great Lakes College of Toronto",
    "St. Thomas University",
    "University Canada West",
    "Douglas College",
  
    "Oxford University",
    "Nottingham Trent University",
    "University of Leicester",
    "University College London",
    "University of Kent",
    "University of Westminster",
    "University of Manchester",
    "University of Newcastle",
    "University of Leeds",
    "De Montfort University",
    "University of Cambridge",
    "Middlesex University",
    "London School of Economics",
    "Birmingham University",
    "Anglia Ruskin University",
    "Brunel University",
    "Essex University",
    "University of Roehampton",
    "University of York",
    "University of Edinburgh",
    "University of Glasgow",
    "Imperial College",
    "University of Portsmouth",
    "Dundee University",
    "University of Central Lancashire",
    "University of East London",
    "University of Aberdeen",
    "University of Plymouth",
    "University of London",
    "University of Birmingham",
    "University of Warwick",
    "University of Lancaster",
    "University of Southampton",
    "Coventry University",
    "University of Exeter",
    "University of East Anglia",
    "Westminster University",
    "London Metropolitan University",
  
    "EU Business School - Spain",
    "IE Business School - Spain",
    "Groningen University - Netherlands",
    "Maastricht University - Netherlands",
    "Utrecht University - Netherlands",
    "Leiden University - Netherlands",
    "University of Amsterdam - Netherlands",
    "Vrije University - Netherlands",
    "Delft University - Netherlands",
    "Radboud University - Netherlands",
    "University of Twente - Netherlands",
    "Tilburg University - Netherlands",
    "Hanze University - Netherlands",
    "ESSCA Business School - France",
    "SciencePo - France",
    "American Business School - France",
    "University of Debrecen - Hungary",
    "Szeged University - Hungary",
    "Debrecen University - Hungary",
    "Lund University - Sweden",
    "Linnaeus University - Sweden",
    "Malmo University - Sweden",
    "University of Galve - Sweden",
    "University of Warsaw - Poland",
    "Vistula University - Poland",
    "Bialystok University of Technology - Poland",
    "Warsaw School of Economics - Poland",
    "University of Liège - Belgium",
    "University of Luxembourg - Luxembourg",
    "Constructor University - Germany",
    "University of Göttingen - Germany",
    "Jacobs University - Germany",
    "EU Business School - Germany",
  
    "Adventist University of Central Africa - Rwanda",
    "African Leadership University - Rwanda",
    "University of Global Health Equity - Rwanda",
    "Catholic University - Kenya",
    "Nazarene University - Kenya",
    "Strathmore University - Kenya",
    "Daystar University - Kenya",
    "United States International University - Kenya",
    "Makerere University - Uganda",
    "University of Johannesburg - South Africa",
    "University of Pretoria - South Africa",
    "University of Cape Town - South Africa",
    "Griffith University - Australia",
    "Murdoch University - Australia",
    "Deakin University - Australia",
    "Monash University - Australia",
    "University of Sydney - Australia",
    "Edith Cowan University - Australia",
    "University of Melbourne - Australia",
    "University of Adelaide - Australia",
    "Middlesex University - Mauritius",
    "African Leadership University - Mauritius",
    "New York University- Abu Dhabi - UAE",
    "Heriot-Watt University - UAE",
    "Middlesex University - UAE",
    "Murdoch University - UAE",
    "Handong Global University - South Korea",
    "Nanjing University - China",
    "Huazhong University - China",
    "University of Nicosia - Cyprus",
    "Ateneo De Manila - Philippines",
  ];